# Generated by Django 3.0.8 on 2020-07-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNumber', models.IntegerField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('timeCreated', models.DateTimeField(auto_now=True)),
                ('timeUpdated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('s', 'in sysyem'), ('f', 'registered'), ('e', 'executed')], max_length=1)),
                ('category', models.CharField(choices=[], max_length=1)),
            ],
        ),
    ]
