# Generated by Django 3.0.8 on 2020-07-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddComplaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(max_length=256),
        ),
    ]
